apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: migration-intelligence-apps
  description: Migration candidate applications for Konveyor Migration Intelligence
spec:
  type: url
  targets:
    - ./coolstore.yaml
