apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notification-service
  description: "JMS-based notification dispatcher"
  tags:
    - migration-candidate
    - java
  annotations:
    github.com/project-slug: konveyor-ecosystem/notification-service
    konveyor.io/source-technology: java-ee-7
    konveyor.io/target-technology: quarkus-3.8
    konveyor.io/migration-status: pending
    konveyor.io/complexity: medium
spec:
  type: service
  lifecycle: production
  owner: guests
