apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
  labels:
    rhdh.redhat.com/ext-config-sync: "true"
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  app-config-rhdh.yaml: |
    auth:
      environment: development
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true
    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location, Template, Group, User]
      locations:
        - type: url
          target: https://github.com/ibolton336/rhdh-plugins/blob/feat/migration-intelligence/workspaces/konveyor/catalog-entities/all.yaml
